### ISSUE TITLE
make is not working

### ISSUE THREAD

**Issue by manojchamp** [PARC/ccnx-tutorial#1]
I am trying to implement this code but make is not working.

**Comment by walendo** [comment]
Hi, what version of the CCNx distribution are you using, and what is the error you're seeing? Did configure run correctly?

**Comment by manojchamp** [comment]
i am using ccnx 1.0.

**Comment by GlennCScott** [comment]
Without more information on what is not working, it ill be hard to impossible to resolve this issue.

I'm closing it.

Please reopen or create a new issue if this problem persists.
