### ISSUE TITLE
liblongbow.so.1 problem

### ISSUE THREAD

**Issue by chorwonkim** [PARC/ccnx-tutorial#5]
when i typing this code '$CCNX_HOME/bin/metis_daemon --capacity 0 &', a problem occur.

The problem is 'error while loading shared libraries: liblongbow.so.1: cannot open shared object file: No such file or directory'

I already install CCNx_Distillery to Github, so i think it's not a problem about longbow.

What's the problem and what should I do?

**Comment by rayyagar** [comment]
Can u setup an environment variable LD_LIBRARY_PATH='Location where u installed CCNx_Distillery' and then execute the command.

**Comment by walendo** [comment]
As Ramesh said, setting LD_LIBRARY_PATH in your environment should help the apps find the CCNx libraries. The default CCNx_Distillery build puts built libraries in CCNx_Distillery/usr/lib so, for example, setting your LD_LIBRARY_PATH to /path/to/CCNx_Distillery/usr/lib should work.

**Comment by chorwonkim** [comment]
Thanks!!!

**Comment by isolis** [comment]
There are various ways to link libraries to binaries.  We're trying to find a good balance between usability, utility, portability and consistency across systems.  We don't have a final solution yet, but we're trying to improve on what we have. For now, LD_LIBRARY_PATH is your friend.

**Comment by GlennCScott** [comment]
I think this has been addressed above, so I'm closing the issue.

Please reopen or create a new issue if there are follow-on problems.
